repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        types_or: [c, c++, cuda]

  - repo: local
    hooks:
      - id: clang-tidy-debug-coverage
        name: clang-tidy
        entry: clang-tidy
        language: system
        types_or: [c, c++, cuda]
        args:
          - "-p"
          - "cmake-build-debug-coverage"